### ISSUE TITLE
py2puml fails where python -m py2puml succeeds

### ISSUE THREAD

**Issue by elrandira** [lucsorel/py2puml#81] opened 2024-01-26 11:31 UTC
I have examples files that are stored according to this hierarchy

```
test
   __init__.py
   test.py
```

I struggled to run the .exe as I would get either `ModuleNotFoundError: No module named 'test.test'` or an empty file depending on the arguments provided:
```
 py2puml.exe test\test test
@startuml test
!pragma useIntermediatePackages false

footer Generated by //py2puml//
@enduml
```

it turned out that `py2puml.exe test test` doesn't work as expected but `python -m py2puml test test` does.

Would it be possible for you to have a look at it?

edit: I am on windows Windows 10 Enterprise v22H2 with python 3.11.6

**Comment by lucsorel** [comment] 2024-01-26 13:59
hi @elrandira 

Thank you for reporting the issue that I was able to reproduce. Fun fact: the bug occurs because of:
- the order of the paths that Python uses to resolve the module resolution (`PYTHON_PATH` or `sys.path`)
- the order is not the same depending on how you execute py2puml!
- the name of the root folder you used: `test`

In the `python - m py2puml test test` case, the current working directory is first and used to resolve `test.test` (corresponding to `test/test.py`) and it works.

In the `py2puml test test` case, the current working directory is last and the python interpreter finds a `test` subfolder in the folder storing the python standard library and attempts to resolve `test.test` there; which fails.

The fix is simple, I should be able to publish a 0.9.1 version this weekend.

Should you have chosen another name than test, you might not have stumbled on the issue :smiley: thanks again for reporting it.

**Comment by lucsorel** [comment] 2024-01-29 21:04
hello @elrandira 

I fixed the issue you identified. Would you take a couple of minutes to review pull request #82 to validate the fix, please :pray: ?

It is just a small fix with a non-regression test. Then I will release the new version.

**Comment by elrandira** [comment] 2024-01-29 21:06
sure, I can give it a try.

**Comment by elrandira** [comment] 2024-01-29 21:20
So now both `python -m py2puml test test` & `py2puml.exe test test` give me correct Puml

strangely, `py2puml.exe test\test test` and `python -m py2puml test\test test` work but generate an empty Puml

while `py2puml.exe test test.test` and `python -m py2puml test test.test` will give me the 
> ModuleNotFoundError: No module named 'test.test.test'; 'test.test' is not a package

**Comment by lucsorel** [comment] 2024-01-30 09:26
:pray: @elrandira for your review.

Glad to hear that the fix works.

The last 2 examples fail for logical reasons:

> `py2puml.exe test\test test` and `python -m py2puml test\test test` work but generate an empty Puml

`test\test` is not an existing folder, so `py2puml` finds nothing in it; hence the empty plantuml content

> `py2puml.exe test test.test` and `python -m py2puml test test.test` will give me the
> ModuleNotFoundError: No module named 'test.test.test'; 'test.test' is not a package

You are asking `py2puml` to inspect the `test/` directory (which exists :+1: ), handle it as the `test.test` package when resolving modules. When handling the `test.py` file in it, python tries to import it as the `test.test.test` module; thus expecting a `test/test/test.py` file in the current working directory (which does not exist).

In py2puml call, the 2 arguments (the folders path and the packages path) must be consistent (1.) together, (2) and regarding the current working directory. The world of CLI tools was new to me when I started writing `py2puml` and my understanding of the import mechanism in Python was shallow and I made those arguments mandatory in the CLI, whereas the packages path could be inferred from the folders path. A future merge request would allow to make the the packages path argument optional (or obsolete).

If you are satisfied with the MR, could you approve it by clicking the green `Review changes` button in the https://github.com/lucsorel/py2puml/pull/82/files page, please:

![image](https://github.com/lucsorel/py2puml/assets/3955251/39bf4f5a-193c-4d6a-b759-dbdf54eca6ab)

**Closed** 2024-01-30 11:32 UTC
Labels: bug
