### ISSUE TITLE
Generic path handling for CLI

### ISSUE THREAD

**Issue by mforkel** [lucsorel/py2puml#47] opened 2023-05-16 10:30 UTC
In my first attempt to use the py2puml CLI, I encountered an import problem similar to #21. When I tried to use a relative path for the path argument, the fix from #40 didn't help because the source directory was not in the current directory.

I wrote a small patch for `cli.py` that fixed the problem for me:
```
--- a/py2puml/cli.py
+++ b/py2puml/cli.py
@@ -9,11 +9,6 @@ from py2puml.py2puml import py2puml
 
 
 def run():
-    # adds the current working directory to the system path so that py2puml can import them
-    current_working_directory = str(Path.cwd().resolve())
-    if current_working_directory not in path:
-        path.append(current_working_directory)
-
     argparser = ArgumentParser(description='Generate PlantUML class diagrams to document your Python application.')
 
     argparser.add_argument('-v', '--version', action='version', version='py2puml 0.7.2')
@@ -21,4 +16,10 @@ def run():
     argparser.add_argument('module', metavar='module', type=str, help='the module name of the domain', default=None)
 
     args = argparser.parse_args()
+
+    # add the directory containing the package to the system path so that py2puml can import it
+    directory = str(Path(args.path).parent.resolve())
+    if directory not in path:
+        path.append(directory)
+
     print(''.join(py2puml(args.path, args.module)))
```

Obviously I'm not aware of all the use cases, but I wonder if the CLI argument list could be simplified: If the order of arguments was changed, may be the path argument might not be required if the package was installed or the source directory (with the package's name) was contained in the current directory. If the current directory happened to be a project directory (i.e. contains `setup.py` or equivalent), may be the project could be the default and no argument would be required at all.

**Comment by lucsorel** [comment] 2023-05-22 21:07
hi @mforkel, thank you for reporting your difficulties to use `py2puml` in an unusual way. Your issue is a little bit similar to https://github.com/lucsorel/py2puml/issues/29.

Like many other code quality tools, `py2puml` is meant to be used within the "usual" structure of a Python project (see https://docs.python-guide.org/writing/structure/#sample-repository and the discussion in another issue: https://github.com/lucsorel/py2puml/issues/29), which is in the root folder of the project (that you version in git), sibling to the folder containing the production code (this is the name of the root package of your Python digital service or library), sibling to the the `tests/` folder containing the automated tests.

The fix you suggested would break more usual cases so I won't include it. If you can, refactor the structure of your project to match the one advised by the official Python documentation. Your other suggestions (changing the order of parameters, potentially removing one when they are redundant) are interesting, so I will link them from the original issue and mark this one as a duplicate. I am sorry, I don't have free time to implement it for now (not enough free time); but contributions are welcome.

Duplicate of https://github.com/lucsorel/py2puml/issues/29.

**Closed by lucsorel** 2023-05-22 21:07 UTC

**Comment by mforkel** [comment] 2023-05-24 17:09
Hi @lucsorel, thanks for your reply. Obviously, its your decision whether you include my patch or not. Nevertheless, there are two remarks I'd like to make.

I'm not sure my project structure is that unsual. Some projects use the flat layout, other use the src layout (see https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/). I prefer the src layout because of its advantages for editable installs. And if you search for this topic, it seems I'm not the only one who uses that layout. It seems to be an ongoing debate.

Right now, py2puml's CLI is geared towards the flat layout and does not support the src layout. To run it from the root directory of my project (the directory containing `setup.py`) I created the patch. As far as I can tell, the patched CLI behaves just like before in a flat layout. But I might be missing something here. So may be you could explain a little what you mean by "the fix you suggested would break more usual cases"?

**Comment by lucsorel** [comment] 2023-05-25 09:26
I agree that there are other project layouts.

The issue with the suggested patch is that it breaks the usage on other project layouts (7 unit tests break). As I said beforehand, there is another way of handling this case mentioned in #29 but it is not on the roadmap for now (freetime available and project priority) :smiley:

**Comment by mforkel** [comment] 2023-06-05 13:33
> it breaks the usage on other project layouts (7 unit tests break).

I'm sorry to hear that. And a little surprised. Because I ran the tests in a clone of your repository before I submitted the patch and I ran them again today (without pulling inbetween). On both occasions, all tests passed. Could you may be give me an example of a test that failed and quote the error, so I can determine what might be the trouble with my setup? Thanks in advance!

**Comment by lucsorel** [comment] 2023-06-05 22:30
my bad, adding the following block before parsing the arguments breaks some tests, but adding them after the arguments parsing does not:

```python
    # add the directory containing the package to the system path so that py2puml can import it
    directory = str(Path(args.path).parent.resolve())
    if directory not in path:
        path.append(directory)

```

I agree that the patch does the trick for some project setups, but it just does not make sense to me to pass a filepath to the CLI and to ask the CLI to include its parent path to the system imports. Why not the parent's parent's one?

It would be more explicit to support `py2puml . .` to scan the current directory, or to support calls like `py2puml this-module.py`; but I lack time for that.

**Comment by lucsorel** [comment] 2026-02-18 13:29
hello @mforkel 

I am sorry it took so long for me to address this issue, you may even have forgotten it ☹️
However, I am glad to tell you that `py2puml 0.11.0` fixes it 🎉

If this tool can still be useful for you on your python projects, give it a try and let me know 🙏

Have a nice day.
