### ISSUE TITLE
what about add the functions to the output

### ISSUE THREAD

**Issue by avielas** [lucsorel/py2puml#41] opened 2023-03-28 12:38 UTC

**Comment by lucsorel** [comment] 2023-03-29 08:49
hello @avielas :smiley: 

Thank you for your suggestion. Could you be more specific about what you expect, please?

Would you like the methods of classes to be documented in the class diagram produced by py2puml? In this case, this issue is a duplicate of https://github.com/lucsorel/py2puml/issues/11. You could also help @jonykalavera on this topic.

Or would you like basic functions to be documented (although they are not classes) in terms of parameters and returned value? In this case, this issue could be linked with this stalled pull requests: https://github.com/lucsorel/py2puml/pull/12

**Comment by avielas** [comment] 2023-03-29 12:37
#11  is exactly what I mean

**Comment by lucsorel** [comment] 2023-03-30 11:40
ok, so I will mark this issue and mark it as a duplicate, if you don't mind :smiley:

**Comment by lucsorel** [comment] 2023-03-30 11:41
Duplicate #11

**Closed by lucsorel** 2023-03-30 11:41 UTC
Labels: duplicate
