### ISSUE TITLE
Can run py2puml only on py2puml

### ISSUE THREAD

**Issue by smarkwart** [lucsorel/py2puml#33] opened 2022-11-09 07:24 UTC
Hi,

I'm able to execute your example, but was not able to run it without errors on my own code.

So, I made a small experiment. I placed a minimal class called myminiclass.py with the below content within the folder py2puml/domain

```
class MyMiniClass(object):
    def __init__(self, instance_name: str):
        self.name = instance_name

    def get_name(self) -> str:
        return self.name
```

The effect is now when running `py2puml py2puml/domain py2puml.domain ` I get the error below:

```
Traceback (most recent call last):
  File "C:\Users\myuser\.conda\envs\myenv\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\myuser\.conda\envs\myenv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\myuser\.conda\envs\myenv\Scripts\py2puml.exe\__main__.py", line 7, in <module>     
  File "C:\Users\myuser\.conda\envs\myenv\lib\site-packages\py2puml\cli.py", line 17, in run        
    print(''.join(py2puml(args.path, args.module)))
  File "C:\Users\myuser\.conda\envs\myenv\lib\site-packages\py2puml\py2puml.py", line 17, in py2puml
    domain_item_module: ModuleType = import_module(name)
  File "C:\Users\myuser\.conda\envs\myenv\lib\importlib\__init__.py", line 127, in import_module    
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'py2puml.domain.myminiclass'
```

When I delete the file everything is working again for the example. Any ideas / suggestions?

Update:

I have one own python package which I installed in my conda environment. For this I'm able to run py2puml as long as I'm in the conda environment it is installed in. But when I create a new conda environment without it I get the same kind of error again.

**Comment by lucsorel** [comment] 2022-11-17 21:48
hello @smarkwart 

Thank you for reporting your issue. Unfortunately, I failed to reproduce the error:
- I created the `33-myminiclass-issue` branch from main to investigate
- I pushed this https://github.com/lucsorel/py2puml/commit/fa628d4d0547ba7f9ed7c4952acb6bdb38447fa2 commit where I:
  -  added the `myminiclass.py` file
  - updated the expected plantuml file
  - ran the unit tests (particulary the `tests/py2puml/test_py2puml.py::test_py2puml_model_on_py2uml_domain` one) and everything works fine

I could also run the `poetry run py2puml py2puml/domain py2puml.domain` command and everything worked fine. It also worked without poetry by manually activating the virtual environment.

```sh
source .venv/bin/activate
py2puml py2puml/domain py2puml.domain
```

Thus I believe your problem is related with the way you created or used the conda environment. I am not very familiar with them. Can you be more specific about how:
- you created the conda environment of your project
- you installed py2puml in your project
- you used py2puml in your project

In a classical project, here is how you are supposed to use py2puml:

```sh
mkdir -p my-project/my_project
cd my-project
python -m venv .venv

# create the myminiclass.py file and then write python code in it
touch my-project/my_project/myminiclass.py

# activate the virtual env and install py2puml
source .venv/bin/activate
pip install py2puml

# run py2puml (my_project appears twice in the command: 1st as folder name, 2nd as a module name - I know this is not optimal)
py2puml my_project my_project
```

Can you provide such commands for your conda setup, please?

**Comment by lucsorel** [comment] 2022-11-28 21:14
hello @smarkwart 

I hope you are doing well. Given that I could not reproduce the issue you faced and the lack of answers, I chose to close the issue for now.

Feel free to reopen it when you have more details :+1:

**Closed by lucsorel** 2022-11-28 21:14 UTC
Labels: question

**Comment by micdonato** [comment] 2023-04-26 18:20
I have the same issue. I can run `py2puml` only on its repository.

I added `miniclass.py` in `py2puml/domain` but I get the error:

```
Traceback (most recent call last):
  File "/home/user/.virtualenvs/poetry_virtualenv_name/bin/py2puml", line 8, in <module>
    sys.exit(run())
  File "/home/user/.virtualenvs/poetry_virtualenv_name/lib/python3.10/site-packages/py2puml/cli.py", line 24, in run
    print(''.join(py2puml(args.path, args.module)))
  File "/home/user/.virtualenvs/poetry_virtualenv_name/lib/python3.10/site-packages/py2puml/py2puml.py", line 12, in py2puml
    inspect_package(
  File "/home/user/.virtualenvs/poetry_virtualenv_name/lib/python3.10/site-packages/py2puml/inspection/inspectpackage.py", line 19, in inspect_package
    domain_item_module: ModuleType = import_module(name)
  File "/fn/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'py2puml.domain.miniclass'
```

I am working from inside poetry's virtual environment. Maybe the package needs to be installed in the virtual environment?

**Comment by micdonato** [comment] 2023-04-27 21:03
Yeah after I installed it in my project poetry env as a dev dependency it worked. I would see some problems if any of the dependencies of `py2puml` conflicts with those of my package, but so far so good.
Thanks!

**Comment by lucsorel** [comment] 2023-04-27 21:14
`py2puml` has no dependency (except pytest as a dev dependency, but it won't be installed), don't worry :wink:
