### ISSUE TITLE
Docstring support 

### ISSUE THREAD

**Issue by ShovanSarker** [lucsorel/py2puml#48] opened 2023-05-18 12:06 UTC
I have a feature request for this project that I would like to propose. I think, the addition of this feature would greatly enhance the project's functionality and usability.

### Description
The proposed feature is to incorporate a standardized function, such as __doc__, that enables retrieving the docstrings for classes and methods and seamlessly inserting them into the UML diagram. This addition would significantly contribute to clarifying the purpose and functionality of classes within the UML representation. It would provide developers with a convenient and consistent way to access the documentation, resulting in improved understanding and maintainability.

### Previous Status
Furthermore, I am unsure whether this feature has been requested previously. If it has, I kindly request information regarding its current status or any ongoing efforts to implement it.

**Comment by lucsorel** [comment] 2023-05-22 20:33
Duplicate of https://github.com/lucsorel/py2puml/issues/34.

Thank you for posting feature requests, but please check beforehand whether a similar issue already exists. There are only 10 open issues, it is easy to check :smiley: 

You can contribute on #34 to suggest how the docstring of a module and a data structure (class, enum, dataclass, etc.) should appear in the generated PlantUML documentation (see https://github.com/lucsorel/py2puml/issues/34#issuecomment-1352265035), that would help implementing something satisfying. Thanks :pray:

**Closed by lucsorel** 2023-05-22 20:33 UTC
