### ISSUE TITLE
support union types in type annotations

### ISSUE THREAD

**Issue by dakebusi** [lucsorel/py2puml#45] opened 2023-04-17 10:48 UTC
When using Union types annotations, e.g. `int | float` the script crashes with an error 

`File "/xxxx/py2puml/parsing/astvisitors.py", line 215, in shorten_compound_type_annotation`

`ValueError: Could not resolve type int | float in module `

It'd be useful to be able to support this.

**Comment by lucsorel** [comment] 2023-04-18 13:56
hi @dakebusi 

Thank you for reporting this issue. `py2puml` should definitely support union types, this is on the roadmap but I have no deadline estimate to provide, unfortunately. Any help on this topic is welcome.

**Comment by Baukebrenninkmeijer** [comment] 2023-06-27 11:23
Just wanted to chime in and agree on support for this feature. Would be greatly appreciated, especially since more codebases are moving into p310 and up.

**Comment by lucsorel** [comment] 2023-07-02 22:22
**Chimes** are welcome, it is **time** that I need :smiley:

**Comment by Quaditz** [comment] 2023-07-27 09:51
Hello,

I found that e.g.

```
@dataclass
class MyData:
  data: Union[bool, int]
```

works. Also, the following works:

```
@dataclass
class MyData:
  data: Optional[bool]
```

However, the following does not work yet:

```
@dataclass
class MyData:
  data: Optional[Union[bool, int]]
```

Also any of these variations do not work and should be supported:

```
@dataclass
class MyData:
  data: Union[bool, int, None]

@dataclass
class MyData:
  data: bool | int

@dataclass
class MyData:
  data: bool | int | None
```

**Comment by lucsorel** [comment] 2023-08-04 16:08
thank you @Quaditz for your inputs :pray: 

Optionals are not supported yet.

I am surprised that you said that the following worked:

```python
from dataclasses import dataclass
from typing import Optional
@dataclass
class MyData:
  data: Optional[bool]
```

For me it fails for two reasons, related to the fact that the `Optional[bool]` typing signature is dynamically replaced by `Union[bool, None]`:
1. the module does not know `Union` (unless you imported it manually yourself)
2. the module does not know `NoneType` (unless you imported it manually yourself)

Can you tell me how you made it work, please?

**Comment by lucsorel** [comment] 2023-08-05 01:23
hi @dakebusi @Baukebrenninkmeijer @Quaditz

I am happy to tell you that pull-request #51 is ready to be merged so that `py2puml` can handle unions in type annotations :smiley:

Before that, could you review it, please, to check that the feature suits your needs? :pray: 

The commit related with this feature is https://github.com/lucsorel/py2puml/pull/51/commits/7576ce6c9aafe6da2307c31d6c20e80d2aef7c67; it handles test dataclasses such as the ones defined in https://github.com/lucsorel/py2puml/pull/51/commits/7576ce6c9aafe6da2307c31d6c20e80d2aef7c67#diff-3274501d02ab968923fadb7a529ac6f6de87999d14ba8b646cf78612da51c28a.

**Comment by Baukebrenninkmeijer** [comment] 2023-08-10 11:20
@lucsorel Great to hear. Do you have an ETA for when this will be released?

**Comment by lucsorel** [comment] 2023-08-10 13:36
> @lucsorel Great to hear. Do you have an ETA for when this will be released?

hi @Baukebrenninkmeijer

No ETA because it is summer. I will merge the feature when someone approved the #51 PR, so you are welcome to review it if you like :smiley: :pray: 

I took this PR as an opportunity to add continuous integration: unit tests for one part, but also pre-commit hooks such as code formatting and code linting. One PR for two features is bad, it complicates the review process and I apologize for that: most of the changes are caused by the code formatting tool :disappointed: I grouped the 2 things so I could test the CI process while developing a feature.

However, there are only 2 commits dedicated to the support of union types; here they are to facilitate the review process:
- https://github.com/lucsorel/py2puml/commit/d37aa3226706f7103b76c13d55a4d461aa65b27e#diff-3274501d02ab968923fadb7a529ac6f6de87999d14ba8b646cf78612da51c28a
- https://github.com/lucsorel/py2puml/commit/d37aa3226706f7103b76c13d55a4d461aa65b27e#diff-2b1143abba365d116d889952b4552da59613ceb446d4da56fe7155ed88ffb3da

**Comment by Quaditz** [comment] 2023-08-12 13:20
> hi @dakebusi @Baukebrenninkmeijer @Quaditz
> 
> I am happy to tell you that pull-request #51 is ready to be merged so that `py2puml` can handle unions in type annotations 😃
> 
> Before that, could you review it, please, to check that the feature suits your needs? 🙏
> 
> The commit related with this feature is [d37aa32](https://github.com/lucsorel/py2puml/commit/d37aa3226706f7103b76c13d55a4d461aa65b27e); it handles test dataclasses and class constructors such as the ones defined in [d37aa32#diff-3274501d02ab968923fadb7a529ac6f6de87999d14ba8b646cf78612da51c28a](https://github.com/lucsorel/py2puml/commit/d37aa3226706f7103b76c13d55a4d461aa65b27e#diff-3274501d02ab968923fadb7a529ac6f6de87999d14ba8b646cf78612da51c28a) - the corresponding unit test is in [d37aa32#diff-2b1143abba365d116d889952b4552da59613ceb446d4da56fe7155ed88ffb3da](https://github.com/lucsorel/py2puml/commit/d37aa3226706f7103b76c13d55a4d461aa65b27e#diff-2b1143abba365d116d889952b4552da59613ceb446d4da56fe7155ed88ffb3da).
> 
> [edit]: I changed the commit and test urls to include changes required to handle union types in class constructors as well.

Great to hear, thanks!

I don't know why this Optional[bool] already worked before, I am taking py2puml from pip, then create one file with one dataclass that contains one Optional[bool] and it works.

Even this works aleardy with py2puml 0.7.2 from pip:

```
@dataclass
class NiceParams:
  test_param: bool

@dataclass
class CrazyParams:
  test_param: bool

@dataclass
class NoParams:
  # Empty

@dataclass
class MyClass:
  params: Union[NiceParams, list[CrazyParams], NoParams]
```

What doesnt work is when I replace NoParams with None:

```
@dataclass
class NiceParams:
  test_param: bool

@dataclass
class CrazyParams:
  test_param: bool

@dataclass
class MyClass:
  params: Union[NiceParams, list[CrazyParams], None]
```

This doesn't work yet. I am no expert to be able to review your code changes completely, but I would say you can merge it when it is able to handle the below use case while not braking all the old unit tests :P

**Comment by lucsorel** [comment] 2023-08-17 16:24
Hi @Quaditz 

> I don't know why this Optional[bool] already worked before, I am taking py2puml from pip, then create one file with one dataclass that contains one Optional[bool] and it works.

Yes, that syntax already worked. It is the new `int | float` syntax (brought by Python 3.10) that did not work.

> What doesnt work is when I replace NoParams with None:

```python
@dataclass
class MyClass:
  params: Union[NiceParams, list[CrazyParams], None]
```

Having None in the unioned types now works (at runtime, `None` is replaced by its type class - `NoneType` - by the Python interpreter; the `py2puml` tool needed to handle that): see https://github.com/lucsorel/py2puml/pull/51/files#diff-3274501d02ab968923fadb7a529ac6f6de87999d14ba8b646cf78612da51c28aR10-R22 :smiley: 

> I am no expert to be able to review your code changes completely, but I would say you can merge it when it is able to handle the below use case while not braking all the old unit tests :P

I understand, but as this project receive several feature requests, it is important for me to involve the community in the review process too, as far as people can give some time to do it. Implementing these features also imply that I must improve my Python level and that I take on my personal time. It is not a product I am paid to develop :wink:

**Closed** 2023-08-28 08:17 UTC
Labels: enhancement, waiting for review

**Comment by lucsorel** [comment] 2023-08-28 08:25
Thanks to the review of https://github.com/grayfox88 and https://github.com/stiebels, `py2puml` now supports union types with version `0.8.0`, which is now available at https://pypi.org/project/py2puml/ :partying_face:

**Comment by Quaditz** [comment] 2023-08-29 18:09
Thank you guys! To all 3 :)

**Comment by lucsorel** [comment] 2023-08-29 19:41
let me know if the feature fulfills your needs
